### ISSUE TITLE
Todays build

### ISSUE THREAD

**Issue by Adminisnyator** [WayfireWM/wcm#27]

**Comment by ammen99** [comment]
what is the exact issue here?

**Comment by Adminisnyator** [comment]
Oh sorry. Did not mean to send it yet. Somehow misclicked. Anywho, the current git version of wf-config paired together with wayfire (both from master each) cause:
 terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

**Comment by Adminisnyator** [comment]
I

**Comment by ammen99** [comment]
> Oh sorry. Did not mean to send it yet. Somehow misclicked. Anywho, the current git version of wf-config paired together with wayfire (both from master each) cause:
> terminate called after throwing an instance of 'std::logic_error'
> what(): basic_string::_M_construct null not valid

Is this crash happening in WCM or in Wayfire?

**Comment by damianatorrpm** [comment]
in wayfire, same thing here

**Comment by damianatorrpm** [comment]
i mean wcm

**Comment by Adminisnyator** [comment]
Not a priority one though. Bye the way, in what way should I report such finds in the future? Ill be staying at the newest build for a bit and do not want to spam the issues area.

**Comment by ammen99** [comment]
I think opening issues is fine :)

**Comment by soreau** [comment]
I believe this bug was recently fixed in wcm. Does it happen with latest wcm from git?

**Comment by Adminisnyator** [comment]
Still happening with a rebuild a few minutes ago. Rebuilt wayfire, wcm, wf-config, wayfire-plugins-extra all from latest master each.

**Comment by soreau** [comment]
What is happening exactly? wcm is crashing?

**Comment by Adminisnyator** [comment]
Wcm crashes on start. Gives the above error message.

**Comment by soreau** [comment]
I am pretty sure this has already been fixed in wcm git master.

**Comment by Adminisnyator** [comment]
Did  a rebuild, it persists. 
[wcm.log](https://github.com/WayfireWM/wcm/files/5754957/wcm.log)
Any other logs that might help?

**Comment by soreau** [comment]
Is there any way you can post a backtrace from gdb?

**Comment by Adminisnyator** [comment]
Copy of bt for future ref
[gdb.log](https://github.com/WayfireWM/wcm/files/5755047/gdb.log)

**Comment by soreau** [comment]
Ah, this is a new breakage caused by latest wf-config changes. I'm not sure how to fix it.

**Comment by soreau** [comment]
I have pushed a fix, pleae reopen if it still crashes for you. Thanks for the report.
